oacore/about

components/pages/markdown.jsx, pages/data-providers.jsx
On desktop, text is too many columns wide
=> Content width

components/bootstrap/_variables.scss
Use 0.5 instead 0.75rem, considered singular line-height
=> reduce Header navbar height

.travis.yml, data/accessibility.md, data/faq.yml, data/home.yml, data/privacy.md, package.json, yarn.lock
Added automatic links checking with [Broken Link Checker](https://github.com/stevenvachon/broken-link-checker) help.
Added 3 testing commands:
- `yarn test-dev` for testing development environment, added exceptions for all reverse-proxies; runs here on GitHub with TravisCI (have a look on _Checks_ tab)
- `yarn test-local` for local testing; the same as above with skipping external links
- `yarn test` for complete integration testing, has no exceptions from above
It would be great to add integration testing on Jenkins with all the proxies set up.
=> Automated links testing (even external ones!)

data/services.yml, pages/services/index.jsx, pages/services/services.scss
Added a basic example of video about CORE Services aka _CORE video 2_.
=> Add video about CORE Services

data/ref-audit.md, pages/ref-audit.jsx
http://localhost:3000/ref-audit
=> Add REF OA audit page

.gitignore, components/repositories-browser/index.jsx, webpack/data-loader.js, webpack/statistics.json
Adds caching mechanism for statistics for local development
without internet connection or for the cases when API is down.
=> Add statistics caching

.lintstagedrc, components/repositories-browser/index.jsx
Closes https://github.com/oacore/next/issues/9
=> Allow to search without accent

pages/about/about.module.scss, pages/about/index.jsx, pages/index.jsx, pages/index.module.scss, pages/services/index.jsx, pages/services/services.module.scss
This is a leftover after #223. I did not apply modules before, we lost some styles.
@PMRuma this should fix the styles. Please, check the _Preview_ below.
=> Fix Next.js CSS modules for individual pages

components/page/page.jsx, data/accessibility.md
* Add missing title
* Add default title to prevent title undefined error
=> Add missing title (#234)

data/services/connector.yml
@viktor-yakubiv Feel free to add an image there if you have any.
=> Remove missing screenshot

components/pages/service.jsx, components/pages/service.module.scss
This slightly adjusts testimonial section on the service pages.
I see some weird borders in accordions appearing locally which don't exist on production.
=> Fix testimonial section on Service pages

next.config.js
Causes hard refresh on any change. @viktor-yakubiv I hope we don't need this polyfill. If we do I will find another solution. Let me know. :)
=> Fix applying polyfills

data/services/repository-dashboard.yml
Add South Africa to repository dashboard 
https://kmi-ou.atlassian.net/browse/CORE-3523?focusedCommentId=42610&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42610
=> Add South Africa to repository dashboard

data/faq.yml
Update FAQ-Aggregation-General 
Add a question Who owns the rights of the content in the CORE collection?
=> Add question to General-Who owns the rights

components/header/index.jsx, package-lock.json, package.json
1. Installs react-ga
2. Creates an event logger for tracking navigation events
3. Embeds event tracking to all the links in the navigation bar
---
@Joozty will ReactGA be initialised if there is NextGA embedding already?
=> Add event tracking to the header navigation

components/repositories-map/index.jsx
Fixes the problem with throttling Wikipedia Map.
=> Change maps to OpenStreetMap

pages/about/about.module.scss
I merged it into the wrong branch 😄
=> Revert wrong urls

package-lock.json, package.json
Nothing really needed here. We just bump it to get a new header layout. Should be released together with @oacore/search
=> Bump design

data/documentation/dataset.md
Update licenses and add new dataset
=> Add licenses to the datasets

data/about.yml, pages/about/index.jsx
Text from, version C https://docs.google.com/document/d/1L-8qv3hT_9YNuI3QFvxlnLYkUeWKM6oxdKr8hVYGCaU/edit?ts=60199083
=> Update the mission statement

data/about.yml, data/services.yml
https://docs.google.com/document/d/1fkrOUUclYRJPx2tKCybDeX37IdJdBG9JPhY_PgpYDO4/edit#
=> Update page according to Bethany's comments

README.md
Adds line explaining to set the Github token to the environment variable
NPM_TOKEN
=> 📘 Improve existing documentation. Add project structure and note about Netlify CMS

.github/workflows/pull-request-check.yml
1.  Splits build and lint jobs
2.  Adds actions/cache to cache `node_modules` speeding up the installation
3.  Upgrades actions/setup-node to version 2
3.  Adds names to every job and every step to make email reports more human-friendly
=> Speed-up CI, improve reporting

data/documentation/dataset.md, data/services/api.yml, data/terms.md
Updates Terms and Conditions, reviews Dataset and API pages, including the documentation to fit into the Terms.
=> Review Terms and Conditions, Dataset and API

netlify-cms.config.yml, pages/history/index.jsx
@vv2529 please merge this as soon as possible once you have an empty working directory.
=> History page renames

pages/history.jsx
Enables previewing data, an important but missing feature.
=> Add custom ref support to the History page

data/services/api.yml
Added an alert for the page. I think the text might change.
This is one of the 50 possible solutions to achieve the same, happy to hear if you have any other option.
=> Adds notice for apiv3

core.routes.yml, data/home.yml
Does what it says on the tin :)
=> Changes link in the homepage

package-lock.json
* Update design version
* Move packages to devDependecies
* Update design package version
* Remove unused dependencies
=> Update design version (#458)

components/bootstrap/_variables.scss, components/content/content.scss, data/faq.yml, pages/oai_resolve.module.scss, pages/oai_resolve_form.jsx, pages/oai_resolver.jsx
* Set cypris
* Update thumbnail placeholder (#447)
* update document-placeholder
* Merge from master
* Change document-placeholder
* Add validation for empty fields author
* oai resolve page (#466)
* oai resolve page
* OAI resolver page
* Rm Ds_store
* Error page implement
* Page width
* Page error style
Co-authored-by: Kostiantyn Voskoboinik <50716463+vkot91@users.noreply.github.com>
=> Oai resolver update (#468)

components/content/content.scss
=> Revert "Doc update"

components/content/content.scss
=> Revert "Doc upd"

components/bootstrap/_variables.scss, components/content/content.scss, data/faq.yml, pages/oai_resolve.module.scss, pages/oai_resolve_form.jsx, pages/oai_resolver.jsx
=> Revert "Oai resolver update (#468)"

next.config.js, templates/history/history.module.scss
* CORE-4174 Update OAI resolver (#508)
* update text
* Fix form input
* FAQ update OAI
* FAQ update OAI
* FAQ update OAI
* FAQ update OAI
* Fix column padding
* Update serch box text and services box (#517)
* Add files via upload
* Add files via upload
* Add files via upload
* Delete Founder Chorst Klaus.jpg
* oai assets path
* style fix
Co-authored-by: Kostiantyn Voskoboinik <50716463+vkot91@users.noreply.github.com>
Co-authored-by: Viktoriiapavlenko04 <86836995+Viktoriiapavlenko04@users.noreply.github.com>
=> Oai resolver assets (#532)

package-lock.json, package.json, pages/services/services.module.scss
=> Update post-css-preset-env version (#562)

data/data.yml
=> Update/data page text (#565)

pages/about/index.jsx
=> Fix/anchor link (#573)

data/home.yml
=> Update/home page funders (#588)

hooks/use-input.js, pages/oai_resolver/oai_resolver_form.jsx
* fix
* update placeholder
* Fix on enter
=> FIX/Input_update (#591)

design-v2/components/hero/styles.module.scss
* Update stage files
* Update oai slide
* Update styles
Co-authored-by: Valeriy Budko <valerij.budko@gmail.com>
=> Update/Hero styles (#600)

netlify-cms.config.yml
* Update benefits section and add metadata
* Fix title
=> Fix/Consultancy service sections (#614)

netlify-cms.config.yml
=> Fix/testimonial authors (#619)

netlify-cms.config.yml
* Update related services section
* Add tutle to section
=> Fix/related services (#623)

netlify-cms.config.yml
* Create new CMS page for dataset
* Update icon
=> Create new CMS page for dataset (#629)

components/accordion/accordion.module.scss
* Fix accordion styles
* Fix item styles
=> Fix accordion styles (#642)

core.routes.yml, data/community/home.yml, data/community/supporters.yml, design-v2/components/hero/index.jsx, design-v2/components/layout/styles.module.scss, package-lock.json, package.json, pages/community/community.module.scss, pages/community/index.jsx, pages/community/supporters.jsx
* Create base board of supporters page. Need connection to API.
* Update slug
* Update research url
=> Core 4337/board of supporters page (#665)

data/membership.yml, package-lock.json
* Update design version
* Update text and design version
=> Update/membership text (#671)

data/benefits.yml
* Core 4204/implement consultancy service page (#660)
* Update text
This …
=> Fix/benefits title text issue (#679)

data/services.yml, design-v2/components/layout/styles.module.scss, package-lock.json, package.json, pages/index.jsx, pages/index.module.scss, pages/services/index.jsx, pages/services/services.module.scss
* Fix/benefits title text issue (#679)
* Core 4204/implement consultancy service page (#660)
* Update text
* Revert …
=> Core 4346/update services page (#683)

data/benefits.yml, design-v2/_variables.scss, design-v2/benefits/styles.module.scss
=> Fix/oai resolver text upd (#691)

templates/documentation/components/block.jsx, templates/documentation/index.jsx
=> Feature/oai resolver component (#693)

pages/oai_resolver/oai_resolver.module.scss, pages/oai_resolver/oai_resolver_form.jsx
=> Feature/oai example link (#695)

pages/oai_resolver/oai_resolver.module.scss
=> Feater/oai link (#697)

templates/membership/styles.module.scss
* [CORE-4376] background fix
[CORE-4376]: https://kmi-ou.atlassian.net/browse/CORE-4376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/core 4376 background (#699)

data/services/recommender.yml
* [CORE-4374] Fix recommender button
[CORE-4374]: https://kmi-ou.atlassian.net/browse/CORE-4374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/core 437 recommender button (#701)

data/membership.yml, design-v2/components/membership-table/index.jsx, design-v2/components/membership-table/styles.module.scss, pages/membership/[slug].jsx, templates/membership/index.jsx, templates/membership/prices.jsx, templates/membership/styles.module.scss
* [Feature] Add membership prices
=> Feature/add membersip fee (#703)

data/membership.yml
* [Feature] Add membership prices
* [Feature] Add google form
=> Feature/add membersip fee (#705)

data/membership.yml, design-v2/components/membership-table/index.jsx
* [Feature] Add membership prices
* [Feature] Add google form
* [Feature] Price update
* [Feature] Price update
=> Feature/add membersip fee (#707)

data/membership.yml
* [Feature] Add membership prices
* [Feature] Add google form
* [Feature] Price update
* [Feature] Price update
* [Feature] butn upd
=> Feature/add membersip fee (#709)

data/payment.yml, templates/member/index.jsx
[CORE-4407](https://kmi-ou.atlassian.net/browse/CORE-4407)
=> update: CORE-4407 add membership text

templates/member/index.jsx
* [update] discountInfo for supporting and sustaining
* [update] additionalInfo for supporting and sustaining
=> Bugfix/excluded text for starting (#736)

data/membership.yml
=> update: CORE membership date update

data/membership.yml
* update: CORE membership date update
* test
=> update: CORE membership date update (#742)

netlify-cms.config.yml
* Update faq
* add linking (#754)
* fix missing buttons issue
* feat: CORE-4429 open pdf in new tab
* CORE-4429 babel config
* update dependencies
* [CORE-4431] docs-membership (#773)
* update dataset text
* CORE update api pdf file
* CORE-4458 update terms page (#784)
* update dataset text
* CORE-4458: update terms page
* temporary page
* [bugfix] Config babel/runtime
* Fix. Remove debug code (#794)
* Fix/master content (#798)
* HOTIFIX: search endpoint wasn't creating the right query
* Master update from content (#795)
* Update faq
* add linking (#754)
* fix missing buttons issue
* feat: CORE-4429 open pdf in new tab
* CORE-4429 babel config
* update dependencies
* [CORE-4431] docs-membership (#773)
* update dataset text
* CORE update api pdf file
* CORE-4458 update terms page (#784)
* …
=> Feature/netlify config (#801)

design-v2/components/search-form/index.jsx, pages/index.jsx
[CORE-4498](https://kmi-ou.atlassian.net/browse/CORE-4498)
[CORE-4498]: https://kmi-ou.atlassian.net/browse/CORE-4498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: CORE-4498 slider issue

webpack/data-loader.js
* [bugfix] SStrict catch loader
* [bugfix] Strict catch loader
* [bugfix] Strict catch loader
=> [bugfix] SStrict catch loader (#897)

components/markdown.jsx, data/community/home.yml, design-v2/components/hero/styles.module.scss
* update posi link redirect
* add spacing
=> Update governance description (#912)

hooks/analytics.js, main/index.jsx
* GA4 init
* GA4 title
* GA4 title
=> Feature/ga4 2 (#923)

README.md, hooks/analytics.js, templates/governance/supporters/index.jsx, templates/governance/supporters/supporters.module.scss
* CORE-4559 add show more button
* Docs
---------
=> CORE-4559 add show more button (#931)

data/payment.yml, pages/membership-request-status/success.jsx, store/membership.js, templates/member/form/hooks/use-select.js, templates/member/form/index.jsx, templates/member/form/select.jsx, templates/member/form/styles.module.scss, templates/member/starting/conditions/index.jsx, templates/member/starting/conditions/styles.module.scss, templates/member/starting/verify-registered.jsx, templates/member/starting/verify_anonymous.jsx, templates/member/styles.module.scss, templates/member/success.jsx
* Add module
* Add repoName
* Anonymous text update
* Style add
* Update text field
* Update styles
* Fix preload for repository
=> Core 4522 (#914)

data/payment.yml, templates/member/index.jsx, templates/member/starting/conditions/index.jsx, templates/member/starting/verify_anonymous.jsx, templates/member/styles.module.scss
* CORE-4522: Text upd
* CORE-4522: Text upd #2
=> Feeture/core 4522 text update #2 (#944)

data/endorsements.yml
* Add files via upload
* Add 3 opinion
---------
=> Feature/add three opnion (#947)

netlify-cms.config.yml
* Netlify update
* Netlify update #2
=> Feature/new structure netlify (#963)

netlify-cms.config.yml
* Netlify update
* Netlify update #2
* Netlify update #3
=> Feature/new structure netlify (#965)

data/faq.yml, pages/faq.jsx, pages/index.module.scss
* update faqs data
* add dates
* update date for all sections
=> Core 4636 add tabs to faq (#981)

pages/governance/supporters.jsx, pages/membership/index.jsx
* update file
* undefined issue
=> update file (#1008)

data/home.yml
* update home page
* CORE-4629 name issue
=> update home page (#1010)

data/benefits.yml, design-v2/benefits/GratitudeModal.jsx, design-v2/benefits/benefitsForm.jsx, design-v2/benefits/benefitsSecondStep.jsx, design-v2/benefits/index.jsx, design-v2/benefits/joinForm.jsx, design-v2/benefits/styles.module.scss, report.20230517.140705.4715.0.001.json
* feat: CORE-4518 add join flow design
* merge master
* CORE-4518: steps
* CORE-4518: link update
=> Core 4518 join us flow (#1066)

.gitignore, data/benefits.yml, design-v2/benefits/benefitsForm.jsx, design-v2/benefits/benefitsSecondStep.jsx, design-v2/benefits/styles.module.scss
* feat: CORE-4518 add join flow design
* merge master
* CORE-4518: steps
* CORE-4518: link update
* CORE-4518: update modal render
* CORE-4518: remove report file
=> Core 4518 join us flow (#1079)

data/benefits.yml, data/data.yml, data/faq.yml, data/services/discovery.yml, data/services/repository-dashboard.yml
* Update pack lock (#1068)
* Update pack lock
* Update pull-request check
* Update pull-request check
* Pack lock update (#1070)
* Update pack lock
* Update pull-request check
* Update pull-request check
* Eslint
* text upd
* text upd
=> Harvest to index (#1095)

data/benefits.yml, design-v2/benefits/index.jsx, design-v2/components/list-box/index.jsx
* CORE-4846: update link redirect
* CORE-4847: join form open
=> Core 4846 links ref (#1105)

components/modal/hooks/use-input.js, components/modal/registration/form.jsx, components/modal/registration/index.jsx, pages/index.jsx
* CORE-4793 Fix issue page
* CORE-4793 Fix issue page
* CORE-4793 Fix issue page
=> CORE-4793 Fix issue page (#1129)

netlify-cms.config.yml, pages/governance/supporters.jsx, templates/governance/supporters/index.jsx
* CORE-4888: add supporters to netlify
* CORE-4888: add supporters to netlify
=> Core 4888 netlify supporters (#1155)

netlify-cms.config.yml, pages/governance/advisory.jsx, pages/governance/supporters.jsx, templates/governance/supporters/index.jsx
* CORE-4888: fix file path
* CORE-4888: space issue
* CORE-4888: fix data flow
=> CORE-4888: fix file path (#1158)

data/membership.yml
* CORE: add missing nav item
* CORE: add missing nav item small
=> Core sidbar missing item (#1175)

design-v2/components/membership-table/index.jsx, design-v2/components/membership-table/styles.module.scss, pages/membership/[slug].jsx, templates/membership/prices.jsx, templates/membership/styles.module.scss
* CORE-4966: updated fees
* CORE-4966: add undefined check
* CORE-4966: remove unused check
=> CORE-4966: updated fees (#1195)

components/membership-table/membershipTable.jsx, components/membership-table/styles.module.scss, pages/membership/index.jsx, templates/governance/supporters/index.jsx, templates/membership/index.jsx, templates/membership/styles.module.scss
* CORE-5002: add new member table
* CORE-5002: add link
=> Core 5002 add new member table (#1235)

design-v2/components/pages/service.jsx, design-v2/components/pages/styles.module.scss
* CORE-5082: update logos
* CORE-5082: fix icon view
=> Core 5082 add log (#1266)

.github/workflows/pull-request-check.yml, netlify-cms.config.yml, templates/sponsorships/index.jsx, templates/sponsorships/styles.module.scss
* CORE-5124: add new logo section
* Update pull-request-check.yml
* Update pull-request-check.yml
---------
=> CORE-5124: add new logo section (#1298)

components/pdf-upload/defaultUpload.jsx, components/pdf-upload/index.jsx
* CORE: fix das upload issue
* CORE: fix upload issue
=> Core fix uploader issue (#1323)

components/blog.jsx, components/citation-tabs/manager.jsx, components/citations-modal.jsx
* CORE: update blog page
* CORE: update research outputs modals
=> Core update code sections (#1325)

components/video.jsx, design-v2/components/video/index.jsx
* Update index.jsx
* Update video.jsx
=> Core 5195 email us (#1332)

components/video.jsx, data/contacts.yml, pages/about/index.jsx
=> Email us fix (#1336)

netlify-cms.config.yml
* CORE: update header
* CORE-5231: remove required field
=> Core 5231 update fee (#1364)
